export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const RESET_COUNTER = 'RESET_COUNTER';

//todo modal actions type
export const ADD_MODAL_TOGGLE_VISIBILITY = 'ADD_MODAL_TOGGLE_VISIBILITY'
export const UPDATE_MODAL_TOGGLE_VISIBILITY = 'UPDATE_MODAL_TOGGLE_VISIBILITY'
export const CHANGE_INDEX_STATUS = 'CHANGE_INDEX_STATUS'