export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const RESET_COUNTER = 'RESET_COUNTER';

//todo modal actions type
export const TODO_MODAL_TOGGLE_VISIBILITY = 'TODO_MODAL_TOGGLE_VISIBILITY'
export const CHANGE_TODO_MODAL_DATA = 'CHANGE_TODO_MODAL_DATA'